"""Shared constants for report structuring."""

AUDIO_SECTION_BREAK_GAP_SEC = 8.0
TARGET_AUDIO_SECTION_DURATION_SEC = 300.0
MIN_AUDIO_SECTION_DURATION_SEC = 120.0
MAX_AUDIO_SECTION_CHARS = 3600
TITLE_WORD_LIMIT = 6
